easy_admin:
  design:
    brand_color: '#55967E'
    menu:
      #- label: 'Gestion'
      #  icon: 'home'
       
      #  children:
          - {label: 'Administration'}
          - {entity: 'City', icon: 'globe', label: 'Villes'}
          - {entity: 'Tag', icon: 'tag', label: 'Tags'}
          - {entity: 'User', icon: 'users', label: 'Utilisateurs'}
          - {entity: 'Review', icon: 'comment', label: 'Avis'}
          - {entity: 'Badge', icon: 'award', label: 'Badge'}
          - {label: 'Web site'}
          - {label: 'Accueil', icon: 'home', route: 'accueil'}