easy_admin:
  design:
    menu:
      - label: 'Gestion'
        icon: 'home'
       
        children:
          - {label: 'Administration'}
          - {entity: 'City', icon: 'globe', label: 'Villes'}
          - {entity: 'Tag', icon: 'home', label: 'Tags'}
          - {entity: 'User', icon: 'calendar', label: 'Utilisateurs'}
          - {label: 'Web site'}
          - {label: 'Accueil', icon: 'home', url: 'http://localhost:8000', rel: 'accueil'}