easy_admin:
  entities:
        City:
            label: Villes
            class: App\Entity\City
            list:
                fields:
                    - id
                    - { property: 'name', label: 'Ville' }
                    - { property: 'country', label: 'Pays' }
                    - { property: 'geonameId', label: 'Geoname id' , type: 'integer'}
                    
                actions:
                    - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }

            form: 
                fields:
                    - { property: 'tags', label: 'Tags de la ville' }

            edit:
                title: 'Mettre à jour (# %%entity_id%% )'