easy_admin:
  entities:
        City:
            label: Villes
            class: App\Entity\City
            disabled_actions: ['new']
            list:
                fields:
                    - id
                    - { property: 'name', label: 'Ville' }
                    - { property: 'country', label: 'Pays' }
                    - { property: 'geonameId', label: 'Geoname id' , type: 'integer'}
                    
                actions:
                    - { name: 'show', icon: 'eye', label: false, css_class: 'btn btn-info' }
                    - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }

            form: 
                fields:
                    - { type: 'group', columns: 6}
                    - { property: 'tags', label: 'Tags de la ville' }

            edit:
                title: 'Mettre à jour (# %%entity_id%% )'

            show:
                fields:
                    - id
                    - { property: 'name', label: 'Ville' }
                    - { property: 'country', label: 'Pays' }
                    - { property: 'geonameId', label: 'Geoname id' , type: 'integer'}
                    - { property: 'reviews', label: 'Avis', type: 'array', type_options: 'App\Entity\Review' }
                    - { property: 'tags', type: 'association', type_options: 'App\Entity\Tag' }
                    - { property: 'cityLikes', type: 'association', type_options: 'App\Entity\CityLike' }
                    
               
                    

            