easy_admin:
  entities:
        Review:
            label: Avis
            class: App\Entity\Review
            disabled_actions: ['new']
            list:
                fields:
                    - id
                    - { property: 'isActive', label: 'Désactivé / Publié' }
                    - { property: 'isReported', label: 'Non Signalé / Signalé' }
                    - { property: 'author', label: 'Auteur' }
                    - { property: 'text', label: 'Avis', type: 'raw'}
                    - { property: 'createdAt', label: 'Publié' }
                    