easy_admin:
  entities:
        Review:
            label: Villes
            class: App\Entity\Review
            list:
                fields:
                    - id
                    - { property: 'isActive', label: 'Status' }
                    - { property: 'isReported', label: 'Signalé' }
                    - { property: 'author', label: 'Auteur' }
                    - { property: 'text', label: 'Avis', type: 'raw'}
                    - { property: 'createdAt', label: 'Publié' }
                    