easy_admin:
  entities:
        User:
            label: Utilisateurs
            class: App\Entity\User
            list:
                fields:
                    - id
                    - { property: 'isActive', label: 'Status' }
                    - { property: 'isReported', label: 'Signalé', type: 'toggle'}
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'updatedAt', label: 'Dernière MAJ' }
                    - { property: 'roles', label: 'Rôles' }


                    
                actions:
                    - { name: 'show', icon: 'eye', label: false, css_class: 'btn btn-info' }
                    - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }
                    
            edit:
                fields: 
                    - username
                    - avatar
                    - points
                    - description
                    #- { property: 'birthdate', label: 'Date de naissance', type_options: {'widget': 'single_text'} }

            show:
                fields:
                    - id
                    - { property: 'isActive', label: 'Status' }
                    - { property: 'isReported', label: 'Signalé', type: 'toggle'}
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'birthdate', label: 'Date de naissance'}
                    - { property: 'email', label: 'Contact' }
                    - avatar
                    - { property: 'filenameAvatar', label: 'Avatar', type: 'image', base_path: '/images/avatars/' }
                    - points
                    - description
                    - { property: 'createdAt', label: 'Inscrit' }
                    - { property: 'updatedAt', label: 'Dernière MAJ' }
                    - { property: 'roles', label: 'Rôles' }